cart/urls.py
from django.urls import path
from .views import cart_change, cart_list, cart_checkout
from .views import OrderListView, order_pay


app_name = 'cart'
urlpatterns = [
    path('change/<str:action>-<int:pid>/', cart_change, name="change"),
    path('products/', cart_list, name="products"),
    path('checkout/', cart_checkout, name="checkout"),
    path('orders/', OrderListView.as_view(), name="orders"),
    path('pay/<int:oid>/', order_pay, name="pay")
]

techshed/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('', include('main.urls')),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls'))
)

cart/models.py
from django.db import models

from account.models import User
from main.models import Product
from techshed.validators import PhoneValidator


class Order(models.Model):
    STATUS_NEW = 0
    STATUS_ACCEPTED = 1
    STATUS_REJECTED = 2
    STATUS_IN_DELIVERY = 3
    STATUS_DELIVERED = 4
    STATUS_CLOSED = 5

    PAYMENT_STATUS_NEW = 0
    PAYMENT_STATUS_PREPARE = 1
    PAYMENT_STATUS_COMPLETE = 2
    PAYMENT_STATUS_REJECTED = 3

    user = models.ForeignKey(User, on_delete=models.RESTRICT)
    address = models.TextField()
    phone = models.CharField(max_length=16, validators=[PhoneValidator()])
    zip_code = models.CharField(max_length=20)
    order_total_price = models.DecimalField(decimal_places=2, max_digits=12, default=0)
    status = models.SmallIntegerField(choices=(
        (STATUS_NEW, "New"),
        (STATUS_ACCEPTED, "Accepted"),
        (STATUS_REJECTED, "Rejected"),
        (STATUS_IN_DELIVERY, "In delivery"),
        (STATUS_DELIVERED, "Delivered"),
        (STATUS_CLOSED, "Closed")
    ))
    payment_status = models.SmallIntegerField(choices=(
        (PAYMENT_STATUS_NEW, "New"),
        (PAYMENT_STATUS_REJECTED, "Rejected"),
        (PAYMENT_STATUS_COMPLETE, "Complete"),
        (PAYMENT_STATUS_PREPARE, "Prepare")
    ), default=PAYMENT_STATUS_NEW)
    order_at = models.DateTimeField(auto_now_add=True)


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.RESTRICT)
    product = models.ForeignKey(Product, on_delete=models.RESTRICT)
    amount = models.IntegerField()

cart/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.db.models import F
from django.shortcuts import render, redirect
from django.views.generic import ListView

from cart.form import OrderForm
from cart.models import OrderProduct, Order
from main.models import Product


def cart_change(request, pid, action):
    product = Product.objects.get(id=pid)
    pid = str(product.id)
    cart = request.session.get('cart', {})
    if cart is None:
        cart = {}

    if action == 'inc':
        cart[pid] = min(cart.get(pid, 0) + 1, product.available)
    elif action == 'dec':
        cart[pid] = max(cart.get(pid, 0) - 1, 0)

    if cart[pid] == 0:
        del cart[pid]

    request.session['cart'] = cart

    return redirect('main:product', product.id)


def cart_list(request):
    cart = request.session.get('cart', {})
    if not cart:
        return redirect('main:index')

    products = Product.objects.filter(id__in=cart.keys()).all()
    result = [{
        'p': row,
        'n': cart[str(row.id)],
        'total': cart[str(row.id)] * row.price
    } for row in products]

    return render(request, 'cart/product.html', {
        'list': result,
        'total': sum([row['total'] for row in result])
    })


@login_required
def cart_checkout(request):
    cart = request.session.get('cart', {})
    if not cart:
        return redirect('main:index')

    products = Product.objects.filter(id__in=cart.keys()).all()
    result = [{
        'p': row,
        'n': cart[str(row.id)],
        'total': cart[str(row.id)] * row.price
    } for row in products]

    form = OrderForm()
    if request.method == 'POST':
        form = OrderForm(data=request.POST)
        if form.is_valid():
            # transaction
            with transaction.atomic():
                form.instance.order_total_price = sum([row['total'] for row in result])
                form.instance.status = Order.STATUS_NEW
                form.instance.user = request.user
                order = form.save()

                products = []
                for pid, n in cart.items():
                    k = Product.objects.filter(id=pid, available__gte=n).update(available=F("available") - n)
                    if not k:
                        raise Exception(f"Mahsulot yetarlicha mavjud emas. {pid}={n}")
                    products.append(OrderProduct(order=order, product_id=pid, amount=n))

                OrderProduct.objects.bulk_create(products)

                request.session['cart'] = {}

                return redirect('main:index')

    return render(request, 'cart/checkout.html', {
        'form': form,
        'products': result
    })


class OrderListView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'cart/orders.html'

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


def order_pay(request, oid):
    Order.objects.filter(id=oid, status=Order.STATUS_NEW).update(status=Order.STATUS_ACCEPTED,
                                                                 payment_status=Order.PAYMENT_STATUS_COMPLETE)

    return redirect("cart:orders")

templates/cart/checkout.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}
{% block content %}
    <div class="container mt-3">
    <div class="row">
        <div class="col-lg-9 col-xl-10">
             <form method="post" action="">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Order now</button>
            </form>
        </div>
        <div class="col-lg-3 col-xl-2">
            {% for p in products %}
                <div class="d-flex">
                    <div>{{ p.p.name }}</div>
                    <div class="ms-auto">{{ p.n }}</div>
                </div>
            {% endfor %}
        </div>
    </div>

    </div>
{% endblock %}

templates/cart/orders.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="container">
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-hover">
            <thead>
            <tr>
                <th>ID</th>
                <th>Summa</th>
                <th>Sana</th>
                <th>Status</th>
                <th>Harakat</th>
            </tr>
            </thead>
            <tbody>
            {% for order in object_list %}
                <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.order_total_price }}</td>
                <td>{{ order.order_at }}</td>
                <td>{{ order.get_status_display }}</td>
                <td>{% if order.status == 0 %}
                    <a href="{% url 'cart:pay' order.id %}" class="btn btn-sm btn-success">Pay</a>
                {% endif %}</td>
                </tr>

            {% endfor %}
            </tbody>
        </table>
    </div>
    </div>


{% endblock %}

templates/cart/product.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container">
    <table class="table table-bordered table-hover table-striped">
    <thead>
    <tr>
        <th>Mahsulot</th>
        <th>Narxi</th>
        <th>Savatchada</th>
        <th>Jami</th>
    </tr>
    </thead>
        <tbody>
        {% for row in list %}
        <tr>
        <td>{{ row.p.name }}</td>
        <td>${{ row.p.price }}</td>
        <td>{{ row.n }}</td>
        <td>${{ row.total }}</td>
        </tr>

        {% endfor %}
        </tbody>
    </table>

    <h2>Total: ${{ total }}</h2>
    <hr/>
    {% if user.is_authenticated %}
        <a href="{% url 'cart:checkout' %}" class="btn btn-info">Checkout</a>
    {% else %}
        <a href="#" class="btn btn-info">Login</a>
    {% endif %}
</div>

{% endblock %}