cart/urls.py
from django.urls import path
from .views import cart_change, cart_list, cart_checkout
from .views import OrderListView, order_pay


app_name = 'cart'
urlpatterns = [
    path('change/<str:action>-<int:pid>/', cart_change, name="change"),
    path('products/', cart_list, name="products"),
    path('checkout/', cart_checkout, name="checkout"),
    path('orders/', OrderListView.as_view(), name="orders"),
    path('pay/<int:oid>/', order_pay, name="pay")
]

main/urls.py
from django.urls import path
from .views import MainIndexView, MainAboutView, MainContactView, MainCategoryView, ProductView


app_name = 'main'

urlpatterns = [
    path('', MainIndexView.as_view(), name="index"),
    path('shop-all/', MainCategoryView.as_view(), name="shop-all"),
    path('sale/', MainCategoryView.as_view(discount=True), name="sale"),
    path('product-<int:pk>/', ProductView.as_view(), name="product"),
    path('category-<int:cat_id>/', MainCategoryView.as_view(), name="category"),
    path('about/', MainAboutView.as_view(), name="about"),
    path('contact/', MainContactView.as_view(), name="contact")
]

techshed/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('', include('main.urls')),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls'))
)

main/models.py
from django.db import models
from django.utils.translation import get_language


class Category(models.Model):
    parent = models.ForeignKey('Category', on_delete=models.RESTRICT, blank=True, null=True, default=None)
    name_en = models.CharField(max_length=50)
    name_uz = models.CharField(max_length=50)

    @property
    def name(self):
        return getattr(self, f'name_{get_language()}')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class TopCategory(models.Model):
    STATUS_ACTIVE = 1
    STATUS_INACTIVE = 0

    category = models.ForeignKey(Category, on_delete=models.RESTRICT)
    text_prefix = models.CharField(max_length=100)
    text = models.TextField()
    text_suffix = models.CharField(max_length=100)
    image = models.ImageField()
    status = models.SmallIntegerField(choices=(
        (STATUS_ACTIVE, "Active"),
        (STATUS_INACTIVE, "Inactive")
    ), default=STATUS_ACTIVE)

    class Meta:
        verbose_name = 'Top category'
        verbose_name_plural = 'Top categories'


class Product(models.Model):
    STATUS_NEW = 0
    STATUS_APPROVED = 1
    STATUS_REJECTED = 2

    category = models.ForeignKey(Category, on_delete=models.RESTRICT)
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=12, decimal_places=2)
    has_discount = models.BooleanField(default=False)
    discount_price = models.DecimalField(max_digits=12, decimal_places=2)
    image = models.ImageField(upload_to="products/")
    available = models.IntegerField(default=0)
    sold = models.IntegerField(default=0)
    status = models.SmallIntegerField(choices=(
        (STATUS_NEW, "New"),
        (STATUS_APPROVED, "Approved"),
        (STATUS_REJECTED, "Rejected")
    ), default=STATUS_NEW)
    added_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        indexes = (
            models.Index(fields=('status', '-sold', )),
        )
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from django_filters.views import FilterView

from main.filters import ProductFilter
from main.models import TopCategory, Product


class MainIndexView(TemplateView):
    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        top = [row for row in TopCategory.objects.filter(status=TopCategory.STATUS_ACTIVE).order_by('?').all()[:2]]
        if len(top) == 1:
            top.append(top[0])

        context['top_categories'] = top
        context['top_sold'] = Product.objects.filter(status=Product.STATUS_APPROVED).order_by('-sold')[:6]

        return context


class MainAboutView(TemplateView):
    template_name = 'main/about.html'


class MainContactView(TemplateView):
    template_name = 'main/contact.html'


class MainCategoryView(FilterView):
    queryset = Product.objects.filter(status=Product.STATUS_APPROVED).all()
    discount = False
    template_name = 'main/products.html'
    filterset_class = ProductFilter

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.discount:
            queryset = queryset.filter(has_discount=True)

        cat_id = self.kwargs.get('cat_id')
        if cat_id is not None:
            queryset = queryset.filter(category_id=cat_id)

        return queryset


class ProductView(DetailView):
    model = Product
    template_name = 'main/product.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        cart = self.request.session.get('cart')
        pid = str(self.object.id)
        context['cart_p'] = cart[pid] if cart and pid in cart else 0
        return context

templates/main/about.html
{% extends 'layouts/base.html' %}

{% block content %}
    About
{% endblock %}

templates/main/contact.html
{% extends 'layouts/base.html' %}

{% block content %}
    Contact
{% endblock %}

templates/main/index.html
{% extends 'layouts/base.html' %}
{% load i18n static %}

{% block content %}

    <section class="slider position-relative">
        <div class="position-absolute img1 img show"></div>
        <div class="position-absolute img2 img"></div>
        <div class="position-absolute img3 img"></div>

        <div class="container position-relative">
            <div class="bg-danger px-3 d-inline-block text-white">{% translate "Best Prices" %}</div>
            <div class="h1 mt-3">{% translate "Incredible Prices<br/>on All Your<br/>Favorite Items" %}</div>
            <div class="mb-3 h2 fw-light">{% translate "Get more for less on selected brands" %}</div>
            <a href="#" class="btn rounded-pill text-white px-5 py-2 fw-light">{% translate "Shop Now" %}</a>
        </div>
    </section>

    {% if top_categories %}
    <section>
    <div class="container-fluid py-3">
        <div class="row">
            {% for c in top_categories %}
            <div class="col-lg-6">
            <div style="background-image: url('{{ c.image.url }}')" class="text-white top-category">
                <div class="prefix fw-light">{{ c.text_prefix }}</div>
                <div class="text my-3">{{ c.text|linebreaksbr }}</div>
                <div class="suffix fw-light">{{ c.text_suffix }}</div>
                <a href="#" class="btn rounded-pill bg-white py-2 px-5 mt-3 fw-light">{% translate "Shop" %}</a>
            </div>
            </div>
            {% endfor %}
        </div>
    </div>
    </section>
    {% endif %}

    <section class="container-fluid">
    <div class="row">
        {% for p in top_sold %}
            <div class="col-lg-2 position-relative">
            {% if p.has_discount %}<span class="badge bg-danger text-white sale">SALE</span>{% endif %}
            <a href="{% url 'main:product' p.id %}">
                <img src="{{ p.image.url }}" alt="{{ p.name }}" class="img-fluid" /><br/>
                {{ p.name }}
            </a>
            {% if p.has_discount %}
                <br/>
            <span class="text-primary">${{ p.discount_price }}</span>
            <span class="text-primary text-decoration-line-through">${{ p.price }}</span>
            {% else %}
            <div class="text-primary">${{ p.price }}</div>
            {% endif %}
            </div>
        {% endfor %}
    </div>
    </section>
{% endblock %}

{% block js %}
    <script>
        (function(){
            let images = document.querySelectorAll('.slider > .img')
            let currentIndex = 0;
            setInterval(() => {
                images.forEach(item => item.classList.remove('show'))
                currentIndex = (currentIndex + 1) % images.length;
                images[currentIndex].classList.add('show')
            }, 5000)
        })();
    </script>
{% endblock %}

templates/main/product.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="container mt-3">
        <h1>{{ object.name }}</h1>
        <div class="text-center">
            <img src="{{ object.image.url }}" class="img-fluid" />
        </div>

        {% if object.has_discount %}
            Price: ${{ object.discount_price }}  <del>${{ object.price }}</del> <br/>
        {% else %}
        Price: ${{ object.price }} <br/>
        {% endif %}

        {% if object.available > 0 %}
            {% if cart_p > 0 %}
                <a href="{% url 'cart:change' 'dec' object.id %}" class="btn btn-info">-</a>
                <span>{{ cart_p }}</span>
                <a href="{% url 'cart:change' 'inc' object.id %}" class="btn btn-info">+</a>
            {% else %}
            <a href="{% url 'cart:change' 'inc' object.id %}" class="btn btn-info">Order</a>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

templates/main/products.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="container-fluid">
    <div class="row">
        <div class="col-lg-3 col-xl-2">
            <form method="get">
            {{ filter.form.as_p }}
                <button type="submit">Filtr</button>
            </form>
        </div>
        <div class="col-lg-9 col-xl-10">
            <div class="row">
                {% for p in object_list %}
                <div class="col-lg-3 position-relative">
                {% if p.has_discount %}<span class="badge bg-danger text-white sale">SALE</span>{% endif %}
                    <a href="{% url 'main:product' p.id %}">
                        <img src="{{ p.image.url }}" alt="{{ p.name }}" class="img-fluid" /><br/>
                        {{ p.name }}
                    </a>
                    {% if p.has_discount %}
                        <br/>
                    <span class="text-primary">${{ p.discount_price }}</span>
                    <span class="text-primary text-decoration-line-through">${{ p.price }}</span>
                    {% else %}
                    <div class="text-primary">${{ p.price }}</div>
                    {% endif %}
                </div>
                {% empty %}
                    <div class="col-12">
                        <h1>Mahsulot topilmadi</h1>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    </div>

{% endblock %}