account/urls.py
from django.urls import path
from .views import account_login, account_logout

app_name = 'account'

urlpatterns = [
    path('login/', account_login, name="login"),
    path('logout/', account_logout, name="logout")
]

cart/urls.py
from django.urls import path
from .views import cart_change, cart_list, cart_checkout
from .views import OrderListView, order_pay


app_name = 'cart'
urlpatterns = [
    path('change/<str:action>-<int:pid>/', cart_change, name="change"),
    path('products/', cart_list, name="products"),
    path('checkout/', cart_checkout, name="checkout"),
    path('orders/', OrderListView.as_view(), name="orders"),
    path('pay/<int:oid>/', order_pay, name="pay")
]

main/urls.py
from django.urls import path
from .views import MainIndexView, MainAboutView, MainContactView, MainCategoryView, ProductView


app_name = 'main'

urlpatterns = [
    path('', MainIndexView.as_view(), name="index"),
    path('shop-all/', MainCategoryView.as_view(), name="shop-all"),
    path('sale/', MainCategoryView.as_view(discount=True), name="sale"),
    path('product-<int:pk>/', ProductView.as_view(), name="product"),
    path('category-<int:cat_id>/', MainCategoryView.as_view(), name="category"),
    path('about/', MainAboutView.as_view(), name="about"),
    path('contact/', MainContactView.as_view(), name="contact")
]

techshed/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('', include('main.urls')),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls'))
)

templates/layouts/base.html
{% load i18n helpers static %}
<!doctype html>
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>TechShed</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
<div class="bg-black text-white py-3 px-4">
    <div class="d-flex">
        <i class="bi bi-box-seam me-2"></i>
        {% translate "Free Shipping for orders over 50$" %}
        <a href="{% url 'main:about' %}"
           class="ms-auto me-4 text-white text-decoration-none">{% translate "About" %}</a>
        <a href="{% url 'main:contact' %}" class="me-4 text-white text-decoration-none">{% translate "Contact" %}</a>
        <a href="#" class="me-4 text-white text-decoration-none">{% translate "Help Center" %}</a>
        <a href="tel:+{{ settings.SITE_PHONE_NUMBER }}"
           class="text-white text-decoration-none">{% translate "Call Us" %}
            {{ settings.SITE_PHONE_NUMBER|phone_format }}</a>
    </div>
</div>

<div class="d-flex align-items-center py-2 header px-4">
    <a href="{% url 'main:index' %}" class="text-decoration-none text-black me-5 logo">TechShed</a>
    <form method="get" action="">
        <div class="input-group">
            <input type="text" class="form-control border-0 bg-gray" placeholder="{% translate "Search ..." %}" />
            <button class="btn text-white px-4" type="submit">
                <i class="bi bi-search"></i>
            </button>
        </div>
    </form>
    {% if user.is_authenticated %}
    <a href="{% url 'account:logout' %}" class="text-nowrap ms-auto text-black text-decoration-none me-4"><i class="bi bi-person-circle me-2"></i> {{ user.username }}</a>
    <a href="{% url 'cart:orders' %}" class="text-nowrap text-black text-decoration-none me-4"><i class="bi bi-list me-2"></i> {% translate "Orders" %}</a>
    {% else %}
    <a href="{% url 'account:login' %}" class="text-nowrap ms-auto text-black text-decoration-none me-4"><i class="bi bi-person-circle me-2"></i> {% translate "Login" %}</a>
    {% endif %}
    <a href="#" class="text-nowrap text-black text-decoration-none me-4"><i class="bi bi-heart me-2"></i> {% translate "Favorites" %}</a>
    <a href="{% url 'cart:products' %}" class="text-nowrap text-black text-decoration-none"><i class="bi bi-cart me-1"></i> <span class="rounded-circle px-1 bg-black text-white">{{ cart_n }}</span></a>
</div>
<div class="bg-gray">
    <div class="d-flex py-2 px-4">
        <a href="{% url 'main:shop-all' %}" class="text-decoration-none text-black fw-light me-4">{% translate "Shop All" %}</a>
        {% for parent in categories %}
            {% if parent.children %}
            <div class="dropdown">
                <a href="#" class="text-decoration-none text-black fw-light me-4" data-bs-toggle="dropdown">{{ parent.category.name }}</a>
                <div class="dropdown-menu">
                    {% for child in parent.children %}
                    <a href="{% url 'main:category' child.id %}" class="dropdown-item">{{ child.name }}</a>
                    {% endfor %}
                </div>
            </div>
            {% else %}
            <a href="{% url 'main:category' parent.category.id %}" class="text-decoration-none text-black fw-light me-4">{{ parent.category.name }}</a>
            {% endif %}
        {% endfor %}
        <a href="{% url 'main:sale' %}" class="text-decoration-none text-black fw-light me-4">{% translate "Sale" %}</a>
    </div>
</div>

{% block content %}{% endblock %}

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

{% block js %}{% endblock %}
</body>
</html>